version: '3'
services:
  mysql:
    container_name: mysql-nistagram-agent
    image: mysql:5.6.27
    ports:
      - "3309:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./resources/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysqldata:
    driver: local
